### ISSUE TITLE
Setting up the Maze Environment

### ISSUE THREAD

**Issue by hasira09** [PixelCtrl/CtrlTangle#1]
**- Task 01 - Setting up a Background**

- [x] Applying an appropriate background for the game
- [x] Setting up other background features

**- Task 02 - Creating the Maze**

- [x] Here the Maze will be set initially

**Comment by hasira09** [comment]
The mentioned tasks are fully completed
